# Chapter 3 - Exercise 3

1. Tạo array 3x3 với tất cả các giá trị đều là True. In array
2. Cho array 1D có 9 phần tử 0-8 => chuyển thành array 2D (3x3) => In array. Chuyển cột 1 sang
cột 3 và ngược lại. => In array
3. Sử dụng array 2D của câu trên, chuyển dòng 1 sang dòng 2 và ngược lại => In array
4. Sử dụng array 2D của câu trên, Đảo ngược các dòng của array 2D => In array
5. Sử dụng array 2D của câu trên, Đảo ngược các cột của array 2D = > In array
6. Cho h = np.array([[1, 2, 3], [np.NaN, 5, 6], [7, np.NaN, 9], [4, 5, 6]]), kiểm tra xem trong array có
giá trị rỗng nào không?
7. Sử dụng array 2D của câu trên, thay thế giá trị null bằng 0

In [1]:
import numpy as np

In [3]:
# 1. Tạo array 3x3 với tất cả các giá trị đều là True. In array
a = np.ones((3,3), dtype=bool)
print(a)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [7]:
# 2. Cho array 1D có 9 phần tử 0-8 => chuyển thành array 2D (3x3) => In array. Chuyển cột 1 sang cột 3 và ngược lại. => In array
array_1d = np.arange(9)
print(array_1d)
array_2d = np.reshape(array_1d, (3,3))
print(array_2d)

c = array_2d[:, [2,1,0]]
print(c)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[2 1 0]
 [5 4 3]
 [8 7 6]]


In [9]:
# 3. Sử dụng array 2D của câu trên, chuyển dòng 1 sang dòng 2 và ngược lại => In array
print(array_2d)
d = array_2d[[1,0,2], :]
print(d)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[3 4 5]
 [0 1 2]
 [6 7 8]]


In [11]:
# 4. Sử dụng array 2D của câu trên, Đảo ngược các dòng của array 2D => In array
print(array_2d)
e = array_2d[:, ::-1]
print(e)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[2 1 0]
 [5 4 3]
 [8 7 6]]


In [12]:
# 5. Sử dụng array 2D của câu trên, Đảo ngược các cột của array 2D = > In array
print(array_2d)
f = array_2d[::-1, :]
print(f)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[6 7 8]
 [3 4 5]
 [0 1 2]]


In [13]:
# 6. Cho h = np.array([[1, 2, 3], [np.NaN, 5, 6], [7, np.NaN, 9], [4, 5, 6]]), kiểm tra xem trong array có giá trị rỗng nào không?
h = np.array([[1, 2, 3], [np.NaN, 5, 6], [7, np.NaN, 9], [4, 5, 6]])
print(h)
print("Have nan? : ", np.isnan(h).any())

[[ 1.  2.  3.]
 [nan  5.  6.]
 [ 7. nan  9.]
 [ 4.  5.  6.]]
Have nan? :  True


In [15]:
# 7. Sử dụng array 2D của câu trên, thay thế giá trị null bằng 0
print(h)
h[np.isnan(h)] = 0
print(h)

[[ 1.  2.  3.]
 [nan  5.  6.]
 [ 7. nan  9.]
 [ 4.  5.  6.]]
[[1. 2. 3.]
 [0. 5. 6.]
 [7. 0. 9.]
 [4. 5. 6.]]
