# Chapter 3 - exercise 1: Hãy thực hiện các yêu cầu sau:

1. Tạo numpy array có giá trị từ 0 - 9, in array, type, shape
2. Từ numpy array ở câu 1 => tạo arr_odd và arr_even => in 2 array mới này
3. Từ numpy array ở câu 1 => tạo arr_update_1 với các phần tử chẵn giữ nguyên, các phần tử lẻ thay bằng 100 => in kết quả
4. Từ 2 array => tạo arr mới chỉ chứa các phần tử xuất hiện ở cả 2 array, lấy duy nhất, dùng np.intersect1d(a,b)
5. Từ 2 array a và b ở câu trên => Tạo array mới chỉ chứa các phần tử chỉ xuất hiện ở array a, dùng np.setdiff1d(a,b)
6. Cho array e, tạo array f chỉ chứa các phần tử có giá trị từ 5 đến 10 của e
7. Tạo array có 10 phần tử 0, cập nhật phần tử ở vị trí thứ 5 là 1
8. Tạo array có giá trị từ 10 đến 24
9. Cho array k => tạo array l từ k với các phần tử đếu khác 0
10. Từ array của câu trên, thêm 2 phần tử có giá trị là 10, 20 vào cuối array
11. Từ array của câu trên, thêm phần tử có giá trị 100 vào index = 5
12. Từ array của câu trên, xóa phần tử index = 0, 1, 2

In [29]:
# 1. Tạo numpy array có giá trị từ 0 - 9, in array, type, shape
import numpy as np

arr = np.arange(10)

print(arr)
print(type(arr))
print(arr.shape)

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
(10,)


In [30]:
# 2. Từ numpy array ở câu 1 => tạo arr_odd và arr_even => in 2 array mới này
arr_odd = arr[arr%2 != 0]
print('Array số lẻ:')
print(arr_odd)

arr_even = arr[arr%2 == 0]
print('Array số chẵn:')
print(arr_even)

Array số lẻ:
[1 3 5 7 9]
Array số chẵn:
[0 2 4 6 8]


In [31]:
# 3. Từ numpy array ở câu 1 => tạo arr_update_1 với các phần tử chẵn giữ nguyên, các phần tử lẻ thay bằng 100 => in kết quả
arr_update_1 = arr.copy()
print(arr_update_1)
arr_update_1[arr_update_1%2 != 0] = 100
print(arr_update_1)

[0 1 2 3 4 5 6 7 8 9]
[  0 100   2 100   4 100   6 100   8 100]


In [32]:
# 4. Từ 2 array => tạo arr mới chỉ chứa các phần tử xuất hiện ở cả 2 array, lấy duy nhất, dùng np.intersect1d(a,b)
a = np.array([1, 3, 5, 7, 9, 10])
b = np.array([1, 2, 4, 6, 8, 10])
print(a, b)
arr_intersect = np.intersect1d(a, b)
print(arr_intersect)

[ 1  3  5  7  9 10] [ 1  2  4  6  8 10]
[ 1 10]


In [33]:
# 5. Từ 2 array a và b ở câu trên => Tạo array mới chỉ chứa các phần tử chỉ xuất hiện ở array a, dùng np.setdiff1d(a,b)
arr_setdiff = np.setdiff1d(a, b)
print(a, b)
print(arr_setdiff)

[ 1  3  5  7  9 10] [ 1  2  4  6  8 10]
[3 5 7 9]


In [34]:
# 6. Cho array e, tạo array f chỉ chứa các phần tử có giá trị từ 5 đến 10 của e
e = np.array([1, 3, 5, 7, 9, 10, 11, 13])
print(e)
f = e[(e>=5) & (e<=10)]
print(f)

[ 1  3  5  7  9 10 11 13]
[ 5  7  9 10]


In [35]:
# 7. Tạo array có 10 phần tử 0, cập nhật phần tử ở vị trí thứ 5 là 1
g = np.zeros(10)
print(g)
g[4] = 1
print(g)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [36]:
# 8. Tạo array có giá trị từ 10 đến 24
h = np.arange(10, 25)
print(h)

# Đảo ngược array [::-1]
h = h[::-1]
print(h)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
[24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [37]:
# 9. Cho array k => tạo array l từ k với các phần tử đều khác 0
k = np.array([1, 2, 0, 8, 2, 0, 1, 3, 0, 5, 0])
print(k)
l = k[k != 0] # Cách 2: l = k[k.nonzero()]
print(l)

[1 2 0 8 2 0 1 3 0 5 0]
[1 2 8 2 1 3 5]


In [38]:
# 10. Từ array của câu trên, thêm 2 phần tử có giá trị là 10, 20 vào cuối array
print(l)
l = np.append(l, [10])
print(l)
l = np.append(l, [20])
print(l)

# Cách 2: l = np.append(l, [10, 20])

[1 2 8 2 1 3 5]
[ 1  2  8  2  1  3  5 10]
[ 1  2  8  2  1  3  5 10 20]


In [39]:
# 11. Từ array của câu trên, thêm phần tử có giá trị 100 vào index = 5
print(l)
l = np.insert(l, 5, 100)
print(l)

[ 1  2  8  2  1  3  5 10 20]
[  1   2   8   2   1 100   3   5  10  20]


In [40]:
# 12. Từ array của câu trên, xóa phần tử index = 0, 1, 2
print(l)
l = np.delete(l, 0)
print(l)
l = np.delete(l, 0)
print(l)
l = np.delete(l, 0)
print(l)

# Cách 2: l = np.delete(l, [0, 1, 2])

[  1   2   8   2   1 100   3   5  10  20]
[  2   8   2   1 100   3   5  10  20]
[  8   2   1 100   3   5  10  20]
[  2   1 100   3   5  10  20]
